/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package no.hvl.dat250.demos.raincount;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import java.io.File;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneId;

public class App {

    public static void main(String[] args) {
        AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(Config.class);


        // creation
        CommandLineResultPresenter presenter = new CommandLineResultPresenter();
        HowLongAlgorithm algorithm = context.getBean(HowLongAlgorithm.class);

        // params
        LocalDateTime questionTime = LocalDateTime.of(2024, 8, 22, 13, 11, 15);
        OffsetDateTime questionTimeZ = OffsetDateTime.of(questionTime, ZoneId.of("Europe/Oslo").getRules().getOffset(questionTime));

        // behaviour
        long result = algorithm.calculate(questionTimeZ);
        presenter.presentResult(result, questionTimeZ);
    }
}
