/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package no.hvl.dat250.l02;

import java.io.File;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneId;

public class App {

    public static void main(String[] args) {
        // creation
        CommandLineResultPresenter presenter = new CommandLineResultPresenter();
        File f = new File("src/test/resources/forecast1.json");
        WeatherForecastSource source =  new JsonFileBasedForecastSource(f);
        HowLongAlgorithm algorithm = new HowLongAlgorithm(source);

        // params

        // you can try setting different start timestamps, remember that they have to be somewhat in sync with the forecast JSON files
        // Have a look at forecast1.json and forecast2.json to see when they start...
        LocalDateTime questionTime = LocalDateTime.of(2024, 8, 22, 13, 11, 15);
        OffsetDateTime questionTimeZ = OffsetDateTime.of(questionTime, ZoneId.of("Europe/Oslo").getRules().getOffset(questionTime));

        // behaviour
        long result = 0;
        try {
            result = algorithm.calculate(questionTimeZ);
        } catch (HowLongAlgorithm.AlgorithmException e) {
            presenter.presentException(questionTimeZ, e);
        }
        presenter.presentResult(result, questionTimeZ);
    }
}
