services:
  testdb:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: supersecret
    ports:
      - 5432:5432
    networks:
      - pollsnw
    volumes:
      - type: volume
        source: pollsdbvol
        target: /var/lib/postgresql
      - type: bind
        source: /Users/past-madm/Projects/teaching/dat250/dat250public/lectureexamples/l15_containers/schema.up.sql
        target: /docker-entrypoint-initdb.d/schema.up.sql
  pollsapp:
    build:
      context: .
    environment:
      DB_HOST: testdb
      DB_USER: postgres
      DB_PASS: supersecret
    ports:
      - 8080:8080
    networks:
      - pollsnw
networks:
  pollsnw:
volumes:
  pollsdbvol: