create table location (id integer generated by default as identity, latitude float(53) not null, longitude float(53) not null, name varchar(255), primary key (id));
create table observation (location_id integer, measurement_value float(53), timestamp timestamp(6) with time zone, id uuid not null, observation_type varchar(255) check (observation_type in ('TEMPERATURE','PRECIPITATION','WIND')), unit varchar(255), primary key (id));
alter table if exists observation add constraint FKjm4wjij0sgxk5hqeksdotrfvd foreign key (location_id) references location;
