apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-db
  name: my-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-db
  template:
    metadata:
      labels:
        app: my-db
    spec:
      containers:
      - image: postgres:latest
        imagePullPolicy: Always
        name: postgres
        env:
          - name: POSTGRES_PASSWORD
            value: supersecret
        volumeMounts:
          - name: setup-sql
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: setup-sql 
          configMap:
            name: setup-sql
            items:
              - key: SQL_UP
                path: schema.up.sql
