apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-db
  name: my-db
  namespace: default
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: my-db
  type: ClusterIP
