apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: my-pv
  resources:
    requests:
      storage: 128Mi
  storageClassName: hostpath
