apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/past-madm/Projects/teaching/dat250/temp/volumes/my-vol/
  storageClassName: hostpath
