/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    idea
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.11.3")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    api("com.rabbitmq:amqp-client:5.26.0")
    implementation("org.slf4j:slf4j-api:2.0.17")
    implementation("org.slf4j:slf4j-simple:2.0.17")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

idea {
    module {
        isDownloadJavadoc = true
        isDownloadSources = true
    }
}


tasks.register("produce", JavaExec::class) {
    mainClass = "no.hvl.dat250.messaging.SimpleProducer"
    classpath = sourceSets.named("main").get().runtimeClasspath
    group = "messaging"
}

tasks.register("consumer", JavaExec::class) {
    mainClass = "no.hvl.dat250.messaging.SimpleConsumer"
    classpath = sourceSets.named("main").get().runtimeClasspath
    group = "messaging"
}

tasks.register("exhangeProduce", JavaExec::class) {
    mainClass = "no.hvl.dat250.messaging.ExchangeProducer"
    classpath = sourceSets.named("main").get().runtimeClasspath
    group = "messaging"
}

tasks.register("exchangeConsumer", JavaExec::class) {
    mainClass = "no.hvl.dat250.messaging.ExchangeConsumer"
    classpath = sourceSets.named("main").get().runtimeClasspath
    group = "messaging"
}