spring.application.name=polls
spring.datasource.url=jdbc:h2:file:./app
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=drop-and-create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=schema.up.sql
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.drop-target=schema.down.sql