spring.application.name=polls
spring.jpa.properties.jakarta.persistence.jdbc.url=jdbc:postgresql://${DB_HOST}:5432/postgres
spring.jpa.properties.jakarta.persistence.jdbc.user=${DB_USER}
spring.jpa.properties.jakarta.persistence.jdbc.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=drop-and-create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=schema.up.sql
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.drop-target=schema.down.sql